services:
  just_a_forum: 
    build:
      args:
        user: laravel_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: just_a_forum_image
    container_name: just_a_forum_app
    restart: unless-stopped
    depends_on:
      - just_a_forum_mysql
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - just_a_forum_network

  forum_web_server:
    image: nginx:alpine
    container_name: forum_web_server_container
    restart: unless-stopped
    depends_on:
      - just_a_forum
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d
    networks:
      - just_a_forum_network

  just_a_forum_mysql:
    image: mysql:latest
    container_name: just_a_forum_mysql_container
    restart: unless-stopped
    ports: 
      - "3306:3306"
    volumes:
      - just_a_forum_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "just_a_forum"
      MYSQL_USER: "owner"
      MYSQL_PASSWORD: "test1234"
      
    networks:
      - just_a_forum_network

  just_a_forum_phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: just_a_forum_phpmyadmin_container
    restart: unless-stopped
    ports:
      - "8383:80"
    environment:
      PMA_HOST: just_a_forum_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456789

    depends_on:
      - just_a_forum_mysql

    networks:
      - just_a_forum_network

volumes:
  just_a_forum_mysql_data:
    driver: local


networks:
  just_a_forum_network:
    driver: bridge
